
RPC_HEADER_LEN = 4

RPC_DEFAULT_BUFFER_SIZE = 1024

RPC_TIMEOUT = 5

RPC_ENTITY_TYPE_GLOBAL = 0

ERROR_CODE_SUCCESS = 0
ERROR_CODE_METHOD_NOT_FOUND = 1
ERROR_CODE_ENTITY_NOT_FOUND = 2
ERROR_CODE_ENTITY_LOAD = 3
ERROR_CODE_INTERNAL = 4

RPC_WINDOW_SIZE = 128 * 1024
